### ISSUE TITLE
Apptainer instead of Singularity

### ISSUE THREAD

**Issue by srnarum** [CDCgov/aquascope#14]
**What type of help do you need?**

* [x ] Question
* [ ] New Repo
* [ ] Delete Repo
* [ ] User Membership (please make sure new members are familiar with the [CDC open practices](https://github.com/CDCgov/template/blob/master/open_practices.md#profile-setup) and set up their profile with name and org info to help people collaborate with them)
* [ ] Other

The machine that I use has Apptainer, the new name for Singularity. I have tried to adjust the code to allow for apptainer, but it has not been successful. Do you have any recommendations to get the pipeline to run with Apptainer?

**Comment by arunbodd** [comment]
We will be testing apptainer very soon for this pipeline. But, from whatever I gathered, singularity seems to be backwards compatible with apptainer according to their documentation. 
https://apptainer.org/docs/user/latest/singularity_compatibility.html

However, if you are still getting errors, please attach the log file and we will look into it.

**Comment by slsevilla** [comment]
Not going to address
