### ISSUE TITLE
MultiQc Failure - while executing the BAM samples

### ISSUE THREAD

**Issue by vijayamsangeetha** [CDCgov/aquascope#18]
For the NCBI BAM -iontorrent samples (SRR27907050, SRR27907050) MultiQC report failed with the attached error message.

**Logs**
[0a/262f10] Submitted process > NFCORE_AQUASCOPE:AQUASCOPE:FREYJA_VARIANT_CALLING:FREYJA_DEMIX (SRR27907050)
[5c/8bf864] Submitted process > NFCORE_AQUASCOPE:AQUASCOPE:FREYJA_VARIANT_CALLING:FREYJA_BOOT (SRR27907050)
[e1/22a5f1] Submitted process > NFCORE_AQUASCOPE:AQUASCOPE:MULTIQC
**ERROR** ~ Error executing process > 'NFCORE_AQUASCOPE:AQUASCOPE:MULTIQC'
Caused by:
  Process `NFCORE_AQUASCOPE:AQUASCOPE:MULTIQC` terminated with an error exit status (1)
Command executed:
  multiqc \
      --force \
       \
      --config multiqc_config.yml \
  cat <<-END_VERSIONS > versions.yml

<img width="960" alt="multiqc_error" src="https://github.com/CDCgov/aquascope/assets/137292393/1af75a92-2fa3-4332-923f-560cde110e29">

**Comment by slsevilla** [comment]
not seen with testing for v3.0.0. Reopen if it is an issue
