### ISSUE TITLE
Bootstrap Failure as no lineages found in demix file : BAM file testing

### ISSUE THREAD

**Issue by amahale6** [CDCgov/aquascope#19]
The Freyja Boot step fails as no lineages are detected in the Freyja Demix step. 

[b8/c32bfb] NOTE: Process `NFCORE_AQUASCOPE:AQUASCOPE:FREYJA_VARIANT_CALLING:FREYJA_BOOT (SRR27907052)` terminated with an error exit status (1) -- Error is ignored
[7b/54f245] NOTE: Process `NFCORE_AQUASCOPE:AQUASCOPE:FREYJA_VARIANT_CALLING:FREYJA_BOOT (SRR27907050)` terminated with an error exit status (1) -- Error is ignored

<img width="960" alt="Demix_empty_log" src="https://github.com/CDCgov/aquascope/assets/129206909/1c9d7911-f735-4749-890e-13a0973deae8">

![Demix_empty](https://github.com/CDCgov/aquascope/assets/129206909/6fb90e1f-5544-4cbb-a508-7acce7fef9c9)

**Comment by slsevilla** [comment]
Please reopen if seen in v3.0.0
