### ISSUE TITLE
Change ivar trim parameters to reflect reads outside of primer regions

### ISSUE THREAD

**Issue by arunbodd** [CDCgov/aquascope#22]
**Describe the bug**
Currently the ivar trim doesn't output illumina reads outside of the primer region.

**Impact**
Due to the exclusion of -e parameter, we see > 75% drop in reads in the final output.

**To Reproduce**
1. To reproduce this behavior, please drop -e from the ivar trim command: 
`ivar trim -i <input.bam> -b <primer.bed> -q 20`

2. To correct this issue, include "-e (  Include reads with no primers. By default, reads with no primers are excluded )"
`ivar trim -i <input.bam> -b <primer.bed> -e -q 20`

**Expected behavior**
The trimmed bams with exclusion of reads with no primers would look like this in BAM file
![image](https://github.com/CDCgov/aquascope/assets/22992035/948310c8-4405-4ed4-870a-d3b97b026cf7)

After the inclusion of -e, we see a significant difference in reads being reported in the BAM file.
![image](https://github.com/CDCgov/aquascope/assets/22992035/0a5b49ef-06c4-42a5-9caa-26146d4d3830)

**Desktop (please complete the following information):**
 - OS: CentOS7
 - IGV
 - Version 2.16.0

**Comment by slsevilla** [comment]
This was included in v2.0.0
