### ISSUE TITLE
Unmatched reference to the bedfile does not return trimmed reads

### ISSUE THREAD

**Issue by amahale6** [CDCgov/aquascope#23]
**Description :**
Long read sequences are failing in the demix step if the sequence id in the bed file is not matching with the reference.

**Sample name**: SRR21595278.fastq.gz
**Bed file**: https://raw.githubusercontent.com/artic-network/primer-schemes/master/nCoV-2019/V3/nCoV-2019.primer.bed
**Matching reference (MN908947.3)**: https://github.com/CDCgov/aquascope/blob/dev/assets/references/SARS-CoV-2.reference.fasta
**Unmatched reference (NC_045512.2)**: https://figshare.com/ndownloader/files/22700666

**Issue:** 
The test produced error with the unmatched reference (NC_045512.2) to the bed file
![image](https://github.com/CDCgov/aquascope/assets/129206909/394835d5-0c2c-4454-9e35-9a4587003879)
![MicrosoftTeams-image (1)](https://github.com/CDCgov/aquascope/assets/129206909/352290b0-5fc1-4d92-89b3-f8c7249ce268)

 **Reproduce Error:**
Command used:
nextflow run main.nf -profile singularity,rosalind --input assets/samplesheet_lr.csv --fasta /assets/references/wuhan.fa --gff assets/references/wuhan.gff -c /scicomp/reference/nextflow/configs/cdc-dev.config --outdir lr_SRR21595278__Resultmodified

Samplesheet:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/uqu6/AppData/Local/Temp/1/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/uqu6/AppData/Local/Temp/1/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

sample | platform | fastq_1 | fastq_2 | lr | bam_file | bedfile
-- | -- | -- | -- | -- | -- | --
SRR21595278 | nanopore |   |   | /scicomp/home-pure/uqu6/aquascope_feb_test/testing_samples/SRR21595278.fastq.gz |  |https://raw.githubusercontent.com/artic-network/primer-schemes/master/nCoV-2019/V3/nCoV-2019.primer.bed

</body>

</html>

**Comment by vijayamsangeetha** [comment]
Add MN908947.3 and NC_045512.2 in the Alternate name, Assumption is the amplicon clip works so freyja demix might work
Add NC and MN in Altername Name
![image](https://github.com/CDCgov/aquascope/assets/137292393/3ba50127-4e2f-422b-b8d4-f53c306ff5ff)
Amplicon Clip didn’t work 
![image](https://github.com/CDCgov/aquascope/assets/137292393/b63fad12-30cd-424b-88fc-3bf2adf04eb0) 
samtools amplicon clip with NC_045512.2 Bed file gives the clipped bam but frayja demix fails 
![image](https://github.com/CDCgov/aquascope/assets/137292393/9768bbd7-e7ff-4d08-a45e-c9a9f77d588b) 
 Based on this testing, the bed file and the reference file should have matching sequence id for executing the pipeline successfully.
