### ISSUE TITLE
Invalid Samplesheet Value results in empty but "successful" pipeline completion

### ISSUE THREAD

**Issue by jessebyoder** [CDCgov/aquascope#41]
**Describe the bug**
The samplesheet values for "platform" are a picklist, and if a value not on the picklist is submitted it seems like the Aquascope pipeline reports a succesfully completed run, but does not produced output files. 

**Impact**
Lack of an error message made this issue difficult to troubleshoot. 

**To Reproduce**
1. put "ILLUMINA" as platform (case-sensative, it needs to be lower-case)
2. run Aquascope
3. Check logs
5. There is no error, but no outputs are produced

**Expected behavior**
An error message should report that platform entry was invalid and list the valid options, and explain that they are case-sensative (or make them case-insensative)

**Comment by arunbodd** [comment]
Hey Jesse,

Thanks for bringing this to our attention. We will work on it as soon as possible and have an updated bug fix release soon.

-
Arun

**Comment by slsevilla** [comment]
completed with pr #45
