### ISSUE TITLE
Document acceptible bedfile formats

### ISSUE THREAD

**Issue by jessebyoder** [CDCgov/aquascope#42]
**Is your feature request related to a problem? Please describe.**
There is a lack of documentation about the requirements for a bedfile, beyond that it should be a tab-separated file.  There are many formats floating around, and it would be nice to know exactly what is compatible with Aquascope. 

**Describe the solution you'd like**
A description of any required columns or acceptable bedfile formats.

**Comment by slsevilla** [comment]
completed with pr #45
