### ISSUE TITLE
Python 3.9 hardcoded

### ISSUE THREAD

**Issue by jessebyoder** [CDCgov/aquascope#55]
**Describe the bug**
Python 3.9 is hardcoded in [this file](https://github.com/CDCgov/aquascope/blob/main/bin/check_samplesheet.py), which does not need that level of specificity. 

**Impact**
We cannot run Aquascope in our standard container which does not contain python3.9.

**Expected behavior**
This script should be python sub-version agnostic.

**Comment by slsevilla** [comment]
completed with #60
