### ISSUE TITLE
Freyja database update

### ISSUE THREAD

**Issue by adhroso** [CDCgov/aquascope#58]
**Describe the bug**
The freyja update command is used to update the internal lineage information and reference files that Freyja relies on for identifying SARS-CoV-2 lineages from genomic data. These reference files are critical for accurate lineage classification and tracking the evolution of the virus.
 
Currently, Freyja supports only the feather format for reference files. However, the code is hardcoded to expect a CSV file, which causes pipeline failures when using the correct feather format.

**Impact**
Cannot run, test or deploy deploy Acquascope because causes pipeline failures when using the correct feather format.

**To Reproduce**
Run acquascope pipeline

**Expected behavior**
Generate variant calls for test data

**Screenshots**
None

**Logs**
None

**Desktop (please complete the following information):**
 - OS: OS X
 - Browser: chrome
 - Version [e.g. 129]

**Smartphone (please complete the following information):**
N/A

**Additional context**
None

**Comment by slsevilla** [comment]
Adding a scope: this error is not seen if you run with singularity or docker, as it is version controlled to v1.5.0, which is how the module is written. NF-Core has not updated to v1.5.1 which requires feather files and so the pipeline does not yet support this.

**Comment by slsevilla** [comment]
Solution was to update freyja to v1.5.2

fixed with 7d615c8b9bf33272025d0ded0770ed7650db287a
