### ISSUE TITLE
Ability to stop workflow after stage-1

### ISSUE THREAD

**Issue by adhroso** [CDCgov/aquascope#59]
**Is your feature request related to a problem? Please describe.**
Add a flag (e.g., --stop-after-stage1) to the workflow that, when passed by the user, return results of stage 1, and not proceeding to the variant calling step.

**Describe the solution you'd like**
Add a flag (e.g., --stop-after-stage1) to the workflow so the user can determine the flow of the pipeline, e.g. run the entire pipeline, run stage-1, or run  stage-2

**Describe alternatives you've considered**
N/A

**Additional context**
Screenshot shows steps 1-6 that correspond with stage-1
<img width="854" alt="Screenshot 2024-10-04 at 12 53 03 PM" src="https://github.com/user-attachments/assets/175a6c35-e5b3-4a25-8474-0404ab376417">

**Comment by jessebyoder** [comment]
It seems like the Stage 1 and Stage 2 flags could possibly be called "pre_processing" and "post_processing" or similar, which would align with accepted terms in the sequencing community?

**Comment by slsevilla** [comment]
completed with #60
