### ISSUE TITLE
Inconsistent Samplesheet Column Names

### ISSUE THREAD

**Issue by jessebyoder** [CDCgov/aquascope#66]
**Describe the bug**
The samplesheet for the [Freyja entrypoint](https://github.com/CDCgov/aquascope/blob/main/assets/samplesheet_test_bam.csv) of Aquascope has a subset of the columns in the [original samplesheet](https://github.com/CDCgov/aquascope/blob/main/assets/samplesheet.csv) but the column names have been changed.

  SNAME = sample
  BAMFILE = bam_file

**Impact**
This is making it difficult to automate samplesheet generation.

**Expected behavior**
Columns containing the same information should have the same names across samplesheet with a consistent case, and consistent use of underscore etc.

**Comment by slsevilla** [comment]
completed with 2a511d6b013aa67262363669169d33e3c5abd5d1
