### ISSUE TITLE
Repeated Variant Calling

### ISSUE THREAD

**Issue by jessebyoder** [CDCgov/aquascope#67]
**Describe the bug**
The current Aquascope [aquascope.nf workflow](https://github.com/CDCgov/aquascope/blob/main/workflows/aquascope.nf) appears to be doing variant calling twice, once with ivar and then again with Freyja which is ivar under the hood.

*Screenshots**
![image](https://github.com/user-attachments/assets/7229214b-f8ca-44a6-8393-86e9b25ccd8c)

**Comment by slsevilla** [comment]
completed with issue #61
